#!/usr/bin/env python3
"""Generate INDEX.md files for maintained repository directories."""

from __future__ import annotations

import argparse
import os
from pathlib import Path


SKIP_DIR_NAMES = {
    ".git",
    ".godot",
    ".godot-sdk",
    ".dotnet-home",
    ".home",
    ".nuget",
    ".vscode",
    "bin",
    "obj",
    "__pycache__",
    "node_modules",
}

SKIP_DIR_PARTS = {
    ("build", "OriginalRpgBattleDemo.app"),
}


def should_skip_dir(path: Path, root: Path) -> bool:
    if path.name in SKIP_DIR_NAMES:
        return True
    rel_parts = path.relative_to(root).parts
    for skip in SKIP_DIR_PARTS:
        if rel_parts[: len(skip)] == skip:
            return True
    return False


def should_skip_file(path: Path) -> bool:
    return path.name in {".DS_Store"} or path.suffix in {".pyc", ".pyo"}


def iter_index_dirs(root: Path) -> list[Path]:
    dirs: list[Path] = []
    for current, dirnames, filenames in os.walk(root):
        current_path = Path(current)
        dirnames[:] = [
            name
            for name in dirnames
            if not should_skip_dir(current_path / name, root)
        ]
        files = [name for name in filenames if not should_skip_file(current_path / name)]
        if current_path == root or files or dirnames:
            dirs.append(current_path)
    return sorted(dirs)


def rel_display(path: Path, root: Path) -> str:
    if path == root:
        return "."
    return path.relative_to(root).as_posix()


def entry_note(path: Path) -> str:
    if path.name == "INDEX.md":
        return "generated directory inventory"
    if path.name == "README.md":
        return "human-maintained overview"
    if path.name == "AGENTS.md":
        return "repository working rules"
    if path.suffix == ".py":
        return "Python tool/script"
    if path.suffix == ".ts":
        return "TypeScript source"
    if path.suffix == ".cs":
        return "C# source"
    if path.suffix in {".tscn", ".godot", ".cfg"}:
        return "Godot project/scene config"
    if path.suffix == ".json":
        return "JSON data/artifact"
    if path.suffix == ".md":
        return "Markdown document"
    if path.suffix == ".png":
        return "PNG image asset/artifact"
    if path.suffix == ".bin":
        return "binary artifact"
    if path.suffix == ".txt":
        return "text artifact"
    return "file"


def build_index(path: Path, root: Path) -> str:
    rel = rel_display(path, root)
    child_dirs = sorted(
        child
        for child in path.iterdir()
        if child.is_dir() and not should_skip_dir(child, root)
    )
    files = sorted(
        child
        for child in path.iterdir()
        if child.is_file() and not should_skip_file(child)
    )

    lines = [
        f"# Directory Index: `{rel}`",
        "",
        "> Generated by `tools/update_directory_indexes.py`. Refresh this file when files in this directory change.",
        "",
        "## Subdirectories",
        "",
    ]
    if child_dirs:
        for child in child_dirs:
            lines.append(f"- `{child.name}/`")
    else:
        lines.append("- none")

    lines.extend(["", "## Files", ""])
    if files:
        for child in files:
            lines.append(f"- `{child.name}` - {entry_note(child)}")
    else:
        lines.append("- none")

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    root = args.root.resolve()
    changed: list[str] = []
    for directory in iter_index_dirs(root):
        index_path = directory / "INDEX.md"
        content = build_index(directory, root)
        old = index_path.read_text(encoding="utf-8") if index_path.exists() else None
        if old != content:
            changed.append(index_path.relative_to(root).as_posix())
            if not args.check:
                index_path.write_text(content, encoding="utf-8")

    if args.check and changed:
        print("outdated indexes:")
        for item in changed:
            print(item)
        raise SystemExit(1)

    print(f"{'checked' if args.check else 'updated'} {len(changed)} index file(s)")


if __name__ == "__main__":
    main()
